version: '3'
services:
  redis-auth:
    image: redis
    ports:
      - "6379:6379"
  redis-score:
    image: redis
    ports:
      - "6380:6379"
  auth:
    build: ./auth
    ports:
      - "3005:3005"
    environment:
      - REDIS_URL=redis://redis-auth:6379
    depends_on:
      - redis-auth
  motus:
    build: ./motus
    ports:
      - "3000:3000"
  score:
    build: ./score
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis-score:6379
      - REDIS_AUTH_URL=redis://redis-auth:6379
    depends_on:
      - redis-score
      - redis-auth