version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - REDIS_URL=redis://redis:6379

  motus:
    build:
      context: ./motus
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  score:
    build:
      context: ./score
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
