# docker-compose.yaml
version: '3'
services:
  auth:
    build:
      context: ./auth
      dockerfile: DockerFile
    ports:
      - 3005:3005
  motus:
    build:
      context: ./motus
      dockerfile: DockerFile
    ports:
      - 3000:3000
  score:
    build:
      context: ./score
      dockerfile: DockerFile
    ports:
      - 3001:3001