version: '3'

services:
  redis-auth:
    image: redis:latest
    ports:
      - "6379:6379"

  redis-score:
    image: redis:latest
    ports:
      - "6380:6379"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - REDIS_URL=redis://redis-auth:6379

  motus:
    build:
      context: ./motus
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  score:
    build:
      context: ./score
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis-score:6379
